
experiment:
  dataset: datarec2elliot
  data_config:
    strategy: dataset
    dataset_path: /Users/angela/PycharmProjects/DataRec-Dev/usage/pipeline/elliot/elliot
  splitting:
    strategy: fixed
    train_path: /Users/angela/PycharmProjects/DataRec-Dev/usage/pipeline/elliot/train.tsv
    validation_path: /Users/angela/PycharmProjects/DataRec-Dev/usage/pipeline/elliot/validation.tsv
    test_path: /Users/angela/PycharmProjects/DataRec-Dev/usage/pipeline/elliot/test.tsv
  models:
    ItemKNN:
      meta:
        hyper_opt_alg: grid
        save_recs: True
      neighbors: [50, 100]
      similarity: cosine
  evaluation:
    simple_metrics: [nDCG]
  top_k: 10